### ISSUE TITLE
Regex improvemenet

### ISSUE THREAD

**Issue by firasdib** [moczolaszlo/postcss-inline-comment#11]
Just wanted to pop by and say

```
/^\/\/[\s]?.+/
```

is 100% equivalent to

```
/^\/\/.+/
```

but slower.

I would probably also recommend changing the `.+` to `.*`.

Thanks!

**Comment by moczolaszlo** [comment]
Thank you very much Firas!
I released the new version.

**Comment by firasdib** [comment]
Happy to help! Thanks!
