### ISSUE TITLE
Example with Gulp?

### ISSUE THREAD

**Issue by benfrain** [moczolaszlo/postcss-inline-comment#2]
Hi, thanks for this plugin, I really miss this capability in standard CSS too!

I've been trying in vain to get this working inside Gulp. Could you provide an example of how it should work inside a Gulp file?

**Comment by moczolaszlo** [comment]
Hi @benfrain !

Here is the gulp example:
https://gist.github.com/moczolaszlo/6738e0d80e266c98627c

And I updated the Readme.md with this.

**Comment by benfrain** [comment]
Hi @moczolaszlo thanks for that, I've copied your example into a fresh Gulp project (with nothing else running other than PostCSS) but it's not working.

Given this input:

``` css
.thing {
    // width: 100%;
    height: 10px;
}
```

The task runs but generates no output. If I remove the comment so the input is this:

``` css
.thing {
    width: 100%;
    height: 10px;
}
```

The task runs and outputs the rule as is.

Here is the task:

``` javascript
var postcss = require("gulp-postcss");
var postCSS_InlineComment = require('postcss-inline-comment');

gulp.task("css", function(){
    var processors = [
    postCSS_InlineComment
    ];
    gulp.src("preCSS/styles.css")
    .pipe(postcss([ postCSS_InlineComment() ]))
    .pipe(gulp.dest("output"));
});
```

Could you think what else it might be causing this? Thanks for any help.

**Comment by moczolaszlo** [comment]
@benfrain Hmm, and maybe if you don't take a space after the comment characters? So just:
//width: 100%;
(I know, there was the space in Readme.md... :))

**Comment by benfrain** [comment]
I’m back in the office in about 11 hours so will try then and report back. Thanks
