### ISSUE TITLE
Working w/ Grunt

### ISSUE THREAD

**Issue by JoshBeveridge** [moczolaszlo/postcss-inline-comment#3]
Hey there, I'm trying to use this processor with Grunt PostCSS, and after having installed it and required it in my Gruntfile I'm getting "Unknown word Use --force to continue." when I compile my PostCSS.

I'm requiring it as follows:
require('postcss-inline-comment')

Any ideas?

**Comment by moczolaszlo** [comment]
Hello @joshdrink !
Do you use this plugin? https://github.com/nDmitry/grunt-postcss/
It's working for me on this way:
https://gist.github.com/moczolaszlo/3ddf73909c9366cd5374

**Comment by JoshBeveridge** [comment]
@moczolaszlo I do use that plugin, yes. It's odd because my setup is almost identical to yours, the primary difference being that I have a far larger number of requires. Perhaps the load order is affecting the processors?

My Gruntfile:

```
module.exports = function(grunt) {
  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    postcss: {
        options: {
            map: false,
            processors: [
            require('postcss-import'),
            require('autoprefixer-core')({browsers: 'last 3 version'}).postcss,
            require('postcss-nested'),
            require('postcss-mixins'),
            require('postcss-simple-vars'),
            require('postcss-for'),
            require('postcss-inline-comment')
            ]
        },
        dist: {
            expand: true,
            flatten: true,
            src: 'assets/post/*.css',
            dest: 'assets/css/'
        },
    },
    watch: {
        files: ['assets/post/*.css', 'assets/post/*/*.css'],
        tasks: ['postcss'],
        options: {
            livereload: true,
        },
    },
  });
  // Grunt Watch
  grunt.loadNpmTasks('grunt-contrib-watch');
  // Post CSS
  grunt.loadNpmTasks('grunt-postcss');
};
```

**Comment by JoshBeveridge** [comment]
EDIT: Scratch that, it's still spitting out the same error. For some reason it doesn't pick up on the comments at the beginning of my file, and errors out on comments inside my CSS.

@moczolaszlo After reinstalling it fresh, it seems that Grunt is running fine, however the output CSS still contains my commented lines.

```
// =======
    // Things
    // Things
// =======
```

Outputs exactly as is in my processed CSS file.

**Comment by moczolaszlo** [comment]
@joshdrink 
Sorry, but it's impossible (now), because postCSS can't parse the inline comment.
This plugin only works with declarations inside a rule. (See the example in the Readme.md.)

But! The next minor version of postCSS will have custom parsers option. I hope, that will help us. :)

**Comment by JoshBeveridge** [comment]
@moczolaszlo Aha, okay, here's hoping! Thanks for the help!

**Comment by moczolaszlo** [comment]
Welcome :)
