### ISSUE TITLE
Commenting out unused variables doesn't work

### ISSUE THREAD

**Issue by ninjapiraatti** [moczolaszlo/postcss-inline-comment#5]
I don't know if this a bug in the plugin or somewhere else but if I comment out a line with unused variable (admittedly kind of an edge case) I get an error about the variable not being used. Changing the order of plugins has no effect.

**Comment by ScottSmith95** [comment]
+1 I'm running into this error as well.

**Comment by moczolaszlo** [comment]
Hi there!
@ninjapiraatti @ScottSmith95 

I made 3 new tests with various postCSS variable plugins and all passed. Please check it:
https://github.com/moczolaszlo/postcss-inline-comment/blob/master/test/test.js

Or maybe I'm wrong, and I don't understand the real problem. :)
