### ISSUE TITLE
Allow for removal of headers

### ISSUE THREAD

**Issue by GTB3NW** [moczolaszlo/postcss-inline-comment#6]
I'm trying to compile susy, a sass library, the only thing stopping me right now is ironically not syntax but comments. Inline comments are used as headers in susy and postcss throws a fit. I tried this plugin but due to it not being in a node it doesn't get removed. Please could you sort a solution?

Example file: https://github.com/ericam/susy/blob/master/sass/_susy.scss

Thanks :)

**Comment by moczolaszlo** [comment]
Hi @GTB3NW !
I'm sorry, but it's not possible with this plugin.
PostCSS at this time only can parse the css rules, not all the file.
