### ISSUE TITLE
Deprecate project for postcss-scss

### ISSUE THREAD

**Issue by ai** [moczolaszlo/postcss-inline-comment#7]

**Comment by moczolaszlo** [comment]
Why? This is just a little hack. (Quote from you :smile:)

**Comment by ai** [comment]
Because postcss-scss give a better result. Users see you project in Google, try it, it doesn't work like Sass, as result they are unhappy of PostCSS ecosystem.

With a deprecated link they will see postcss-scss and will happy with 100% , same result as in Sass.

**Comment by moczolaszlo** [comment]
Ok, I accept it. :)
I really like PostCSS and that You made, and I don't want problems around it.

**Comment by ai** [comment]
:-D I am not a tyrant :-)

**Comment by moczolaszlo** [comment]
:smile:
