### ISSUE TITLE
What if I don't want to use postcss-scss?

### ISSUE THREAD

**Issue by axe312ger** [moczolaszlo/postcss-inline-comment#8]
Looks like postcss-scss is a bloated plugin which adds multiple features. What if I only want to stripe the single line comments away?

Can you please clearify why you marked your repo deprecated? Thx :)

**Comment by moczolaszlo** [comment]
The postcss-scss plugin is the only reason for that. :)
So you can use my plugin, i won't delete it from npm.
But it's completed, because it's impossible to develop more options/use cases or anything. :)

(But thx for the question, I have to clarify this on the Readme.md!)

**Comment by axe312ger** [comment]
Awesome! Thanks for the reply. Also good work! :)
